### ISSUE TITLE
rendering array of object cause cyclic reference on objects

### ISSUE THREAD

**Issue by lduboeuf** [aishikaty/tiny-mustache#1]
hello,

i have an array that i pass like this: `mustache(tpl, { list: myArrayOfObjects });`
after rendering,  `myObject` have a prototype `myArrayOfObjects` referenced to it after this line of code: 
 https://github.com/aishikaty/tiny-mustache/blob/master/mustache.js#L21 
which leads to `TypeError: cyclic object value` error when serializing array later in my code

Do you know how to get rid of it ?

**Comment by aishikaty** [comment]
Hi @lduboeuf,
sorry for late answer, I didn't notice this issue before.

I guess we shouldn't mess with the object prototype. I believe this could be fixed by replacing the line with:
```javascript
ctx = Object.assign({}, parent, ctx)
```
Please let me know if you could confirm this works, I'm going to test it further.

Thank you for the issue report.
