### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by dylee** [aishikaty/tiny-mustache#2]
https://github.com/aishikaty/tiny-mustache/blob/870c6e59f73cd4e62bfef1f34fcc12c8f7671e48/mustache.js#L21

IE11 does not support [Object.assign](https://docs.microsoft.com/en-us/scripting/javascript/reference/object-assign-function-object-javascript#requirements). I recognize poly fill (with something like [es6-object-assign](https://github.com/rubennorte/es6-object-assign/blob/master/dist/object-assign-auto.min.js)) probably doesn't keep with the spirit of "tiny," but since IE11 has like [12% marketshare](https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0) and it's still supported by MS, compatibility seems warranted.

**Comment by aishikaty** [comment]
@dylee Hi @dylee, thanks for your feedback. I suggest we add a note about compatibility in IE and link to the polyfil in the README. Do you think that would be good enough solution or do you think it needs to be included in the source?

**Comment by aishikaty** [comment]
@dylee Are you sure about the marketshare? When I look at http://caniuse.com/#feat=flexbox, I see 3.13%, it seem to be quite a big difference for just a measurement error?

**Comment by dylee** [comment]
@aishikaty, I suppose these marketshare estimates are just that estimates and can be wildly different, although I wonder if the one you're looking at accounts for mobile, whereas the one that I referred to was for desktop only. In any case, I think adding instructions in the README will suffice. Since I already had jQuery as a dependency in my project it was easy enough to use $.extend. Thank for your work on this lib. Very useful to me!
